### ISSUE TITLE
rep-0199: Vendor "leaf frame" names

### ISSUE THREAD

**Issue by ahoarau** [ros-industrial/rep#29]
Hello,
As I was explaining to one of our interns the naming for industrial manipulators frame names, I got myself a bit confused and had to go back again to this REP to re-discover the problem once again :

- Having "vendor-independent" frames for base and flange
- Having "vendored" frames for base and flange
- Having something called "tool" when it is not representing a physical object

The "base" of the robot, as we all call it, is called `base_link` here, and the vendor name is called `base`. Typical usecase when computingkinematic frames : "This pose is computed with respect to the base of the robot... called base_link. Do not use 'base' as the frame of reference"

The "Tool" pose of the robot is confusing in itself as it can represent:
- The transform between `flange-->eef_tcp` 
- The pose of the visual mesh representing the "thing attached to the robot flange"
- The pose of the tcp frame w.r.t the robot base

As `tool0` is only here as a way to transform poses into the vendored convention, why not call them `base_vendor` and `flange_vendor` ?
Also, why not call `base_link`/`flange `base`/`flange`, or `base_link`/`flange_link` ?

```shell
base
├ base_vendor  # vendored version of the base
└ link_1
  └ ..
    └ link_N
      └ flange
        └ flange_vendor # vendored version of the flange = 'Tool' pose when T(flange->eef_tcp) = Identity
```

Thanks for your comments !

**Comment by gavanderhoorn** [comment]
Thanks for the comment, but first: please check your markup, as I believe something is not entirely correct and it's making things more difficult to understand.

**Comment by gavanderhoorn** [comment]
Actually: please post comments on https://github.com/gavanderhoorn/rep/pull/3, and not in this repository, as the candidate REP is a 'regular' ROS REP, not a ROS-I one.

**Comment by ahoarau** [comment]
Markup is fixed and ref added. Shall I close this one and open in your repo ?
